theme: jekyll-theme-cayman
title: Eftekhar Hossain
description: Hello, welcome to my portfolio. I am passionate about machine learning, natural language processing, computer vision and data science.
github:
  is_project_page: false
